import 'package:flutter/material.dart';import 'package:noor_s_application1/core/app_export.dart';import 'package:noor_s_application1/widgets/custom_elevated_button.dart';class RegisterPoliticatsAndTermsToRegisterScreen extends StatelessWidget {const RegisterPoliticatsAndTermsToRegisterScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 114.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("شروط استخدام التطبيق", style: theme.textTheme.titleMedium)), CustomImageView(imagePath: ImageConstant.imgCancelFill1Wg, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 22.h, bottom: 3.v))]), SizedBox(height: 66.v), Align(alignment: Alignment.center, child: Container(width: 341.h, margin: EdgeInsets.only(left: 11.h, right: 12.h), child: Text("يتبع تطبيقنا بعض السياسات الخاصة للعمل ولتوفير الخدمات\nالإلكترونية للعميل ولضمان الحصول على تجربة ممتعة أثناء\nاستخدام التطبيق.\nيقوم تطبيقنا بجمع بعض البيانات الخاصة للعملاء لنجاح\nاستخدام التطبيق ولجعله أداة لخدمة عملائنا. يحرص فريق\nتطبيق زاد على إخبارك بأنه يجب علينا جمع بعض البيانات التالية : ", maxLines: 7, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.bodyMedium14.copyWith(height: 1.50)))), SizedBox(height: 42.v), Container(width: 314.h, margin: EdgeInsets.only(left: 38.h, right: 12.h), child: Text(" 1- سيتم مشاركة بياناتك الموجودة على ايميلك الإلكتروني\n(الصورة , الاسم , المكان ).\n\n2- سيتم مشاركة رقم هاتفك واسمك وموقعك مع\nالمندوبين.\n\n3- سيتم مشاركة موقعك الحالي أثناء استخدام التطبيق.", maxLines: 8, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.bodyMedium14.copyWith(height: 1.36))), SizedBox(height: 49.v), Align(alignment: Alignment.centerLeft, child: Container(width: 349.h, margin: EdgeInsets.only(left: 2.h, right: 13.h), child: Text("نشكركم على حسن ثقتكم وسنحرص كل الحرص على الاحتفاظ\nبسرية بياناتكم وخصوصيتكم من السرقة أو الاحتيال , لذلك يقدم\nلكم التطبيق دعم فوري في التطبيق للاستجابة السريعة للعميل\nأثناء حدوث أي طارئ بداخل التطبيق.", maxLines: 5, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.bodyMedium14.copyWith(height: 1.50)))), Spacer(), SizedBox(height: 6.v), _buildTf(context)])))); } 
/// Section Widget
Widget _buildTf(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 4.h, right: 13.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 161.h, text: "إلغاء", buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleSmallErrorContainer, onPressed: () {onTaptf(context);}), CustomElevatedButton(width: 157.h, text: "موافق", onPressed: () {onTaptf1(context);})])); } 
/// Navigates to the registerChooseATypeOfAccountsActiveOneScreen when the action is triggered.
onTaptf(BuildContext context) { Navigator.pushNamed(context, AppRoutes.registerChooseATypeOfAccountsActiveOneScreen); } 
/// Navigates to the registerCreateAnAccountAfterAcceptTheTermsScreen when the action is triggered.
onTaptf1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.registerCreateAnAccountAfterAcceptTheTermsScreen); } 
 }
