import 'package:flutter/material.dart';import 'package:noor_s_application1/core/app_export.dart';import 'package:noor_s_application1/widgets/custom_checkbox_button.dart';import 'package:noor_s_application1/widgets/custom_drop_down.dart';import 'package:noor_s_application1/widgets/custom_elevated_button.dart';class RegisterCreateAnAccountPage extends StatefulWidget {const RegisterCreateAnAccountPage({Key? key}) : super(key: key);

@override RegisterCreateAnAccountPageState createState() =>  RegisterCreateAnAccountPageState();

 }

// ignore_for_file: must_be_immutable
class RegisterCreateAnAccountPageState extends State<RegisterCreateAnAccountPage> with  AutomaticKeepAliveClientMixin<RegisterCreateAnAccountPage> {List<String> dropdownItemList = ["Item One", "Item Two", "Item Three"];

bool tf = false;

@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 48.v), SizedBox(height: 557.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 37.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildTextInputAndLabel(context), SizedBox(height: 31.v), _buildTextInputAndLabel(context), SizedBox(height: 29.v), _buildTextInputAndLabel3(context), SizedBox(height: 31.v), _buildTextInputAndLabel(context), SizedBox(height: 29.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(21.h, 11.v, 14.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "بنغازي", items: dropdownItemList, onChanged: (value) {}), SizedBox(height: 29.v), _buildTf1(context), SizedBox(height: 29.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 63.h, right: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [GestureDetector(onTap: () {onTapTxttf(context);}, child: Padding(padding: EdgeInsets.only(top: 1.v, bottom: 7.v), child: RichText(text: TextSpan(children: [TextSpan(text: "إذا كنت تمتلك حساب فيجب عليك ", style: CustomTextStyles.bodySmallErrorContainer12), TextSpan(text: " "), TextSpan(text: "تسجيل الدخول", style: CustomTextStyles.labelLargePrimary_1.copyWith(decoration: TextDecoration.underline))]), textAlign: TextAlign.right))), CustomImageView(imagePath: ImageConstant.imgFlagFill1Wght, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 8.h))])))]))), _buildTf2(context)]))]))))); } 
/// Section Widget
Widget _buildTextInputAndLabel3(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 17.h), child: Text("ادخل الرمز السري", style: CustomTextStyles.titleSmallErrorContainerBold_1))), SizedBox(height: 8.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 9.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgVisibilityFill, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(top: 8.v, bottom: 1.v), child: Text("الرمز السري", style: CustomTextStyles.bodySmallOnError))]))]); } 
/// Section Widget
Widget _buildTf1(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 18.h), child: CustomCheckboxButton(alignment: Alignment.centerRight, width: 179.h, text: "الموافقة على سياسات التطبيق", value: tf, textStyle: CustomTextStyles.bodySmallErrorContainer, isRightCheck: true, onChange: (value) {tf = value;}))); } 
/// Section Widget
Widget _buildTf2(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 356.v, bottom: 48.v), padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 32.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: CustomElevatedButton(text: "إلغاء", margin: EdgeInsets.only(right: 15.h, bottom: 43.v), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleSmallErrorContainer, onPressed: () {onTaptf(context);})), Expanded(child: CustomElevatedButton(text: "إنشاء حساب", margin: EdgeInsets.only(left: 15.h, bottom: 43.v)))]))); } 
/// Common widget
Widget _buildTextInputAndLabel(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 17.h), child: Text("ادخل الإيميل", style: CustomTextStyles.titleSmallErrorContainerBold_1))), SizedBox(height: 11.v), Container(width: 354.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 13.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("الإيميل الإلكتروني", style: CustomTextStyles.bodySmallOnError))]); } 
/// Navigates to the registerLogInTabContainerScreen when the action is triggered.
onTapTxttf(BuildContext context) { Navigator.pushNamed(context, AppRoutes.registerLogInTabContainerScreen); } 
/// Navigates to the registerChooseATypeOfAccountsActiveOneScreen when the action is triggered.
onTaptf(BuildContext context) { Navigator.pushNamed(context, AppRoutes.registerChooseATypeOfAccountsActiveOneScreen); } 
 }
