import 'package:flutter/material.dart';import 'package:noor_s_application1/core/app_export.dart';import 'package:noor_s_application1/widgets/custom_elevated_button.dart';class RegisterLogInForgetAPasswordOneScreen extends StatelessWidget {const RegisterLogInForgetAPasswordOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 59.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 14.v, bottom: 9.v), child: Text("زاد - ZAD", style: CustomTextStyles.labelLargeErrorContainer_1)), CustomImageView(imagePath: ImageConstant.imgEllipse138x38, height: 38.adaptSize, width: 38.adaptSize, radius: BorderRadius.circular(19.h), margin: EdgeInsets.only(left: 13.h))])), SizedBox(height: 73.v), Padding(padding: EdgeInsets.only(right: 10.h), child: Text("نسيت كلمة المرور", style: theme.textTheme.headlineSmall)), SizedBox(height: 70.v), Padding(padding: EdgeInsets.only(right: 10.h), child: _buildTextInputAndLabel(context)), SizedBox(height: 46.v), Padding(padding: EdgeInsets.only(right: 10.h), child: _buildTextInputAndLabel(context)), SizedBox(height: 24.v), Align(alignment: Alignment.center, child: Container(width: 305.h, margin: EdgeInsets.only(left: 31.h, right: 27.h), child: RichText(text: TextSpan(children: [TextSpan(text: "يتوجب عليك فتح بريدك الإلكتروني لمعرفة الرمز السري\n\n", style: CustomTextStyles.bodyMedium14_1), TextSpan(text: "إعادة إرسال الرمز السري؟", style: CustomTextStyles.titleSmallBold_1.copyWith(decoration: TextDecoration.underline))]), textAlign: TextAlign.right))), SizedBox(height: 62.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: SizedBox(width: 281.h, child: Text("ملاحظة : يجب الاحتفاظ بالرمز السري ككلمة سر لحسابك لكي يتم إعادة استخدامه أثناء تعيين الرمز السري وإدخال رمز سري آخر جديد لحسابك, في حالة احتجت لهذا الإجراء.", maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.bodyMedium14.copyWith(height: 1.36)))), CustomImageView(imagePath: ImageConstant.imgWarningFill1W, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 15.h, bottom: 58.v))]))), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(right: 56.h), child: Text("إعادة تعيين الرمز السري", style: CustomTextStyles.titleSmallBold.copyWith(decoration: TextDecoration.underline))), SizedBox(height: 85.v), _buildTf(context)])))); } 
/// Section Widget
Widget _buildTf(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 6.h, right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 162.h, text: "إلغاء", buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleSmallErrorContainer), CustomElevatedButton(width: 161.h, text: "إعادة التعيين", onPressed: () {onTaptf(context);})])); } 
/// Common widget
Widget _buildTextInputAndLabel(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 17.h), child: Text("ادخل الرمز السري", style: CustomTextStyles.titleSmallErrorContainerBold_1))), SizedBox(height: 7.v), Container(width: 354.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 12.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("الرمز السري", style: CustomTextStyles.bodySmallOnError))]); } 
/// Navigates to the ordersScreen when the action is triggered.
onTaptf(BuildContext context) { Navigator.pushNamed(context, AppRoutes.ordersScreen); } 
 }
