import 'package:flutter/material.dart';import 'package:noor_s_application1/core/app_export.dart';import 'package:noor_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:noor_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:noor_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:noor_s_application1/widgets/custom_elevated_button.dart';class OrdersOrderDetailsChooseTimeTwoScreen extends StatelessWidget {const OrdersOrderDetailsChooseTimeTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(height: mediaQueryData.size.height, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.fromLTRB(15.h, 42.v, 20.h, 37.v), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(context), SizedBox(height: 34.v), _buildDescription(context), SizedBox(height: 91.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 139.h, right: 104.h), padding: EdgeInsets.symmetric(horizontal: 46.h, vertical: 41.v), decoration: AppDecoration.outlineErrorContainer7.copyWith(borderRadius: BorderRadiusStyle.circleBorder75), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), SizedBox(width: 58.h, child: Text("الوقت\nالأدنى", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.titleLargePrimary.copyWith(height: 1.50)))]))), SizedBox(height: 91.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 139.h, right: 104.h), padding: EdgeInsets.symmetric(horizontal: 42.h, vertical: 41.v), decoration: AppDecoration.outlineErrorContainer7.copyWith(borderRadius: BorderRadiusStyle.circleBorder75), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), SizedBox(width: 66.h, child: Text("الوقت\nالأقصى", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.titleLargePrimary.copyWith(height: 1.50)))]))), Spacer(), _buildTf(context)]))), Align(alignment: Alignment.center, child: Container(height: mediaQueryData.size.height, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.errorContainer.withOpacity(0.3))))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 28.v, leadingWidth: 43.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 15.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarSubtitle(text: "توصيل الطلبية", margin: EdgeInsets.fromLTRB(29.h, 6.v, 29.h, 4.v))]); } 
/// Section Widget
Widget _buildDescription(BuildContext context) { return Container(margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 31.v), decoration: AppDecoration.outlineErrorContainer7.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 26.v), SizedBox(width: 330.h, child: Text("يجب اختيار الوقت الأدنى والوقت الأقصى لتوصيل طلبية\nالعميل.", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: theme.textTheme.bodyMedium!.copyWith(height: 1.20)))])); } 
/// Section Widget
Widget _buildTf(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 16.h, right: 11.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "رجوع", margin: EdgeInsets.only(right: 18.h), buttonStyle: CustomButtonStyles.fillBlueGrayTL81, buttonTextStyle: CustomTextStyles.titleSmallBlack90003)), Expanded(child: CustomElevatedButton(text: "ارسال", margin: EdgeInsets.only(left: 18.h)))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
